workflows:
  android-apk:
    name: MyHeartAI APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_VERSION: 18
      flutter: stable
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Change directory to android
        script: cd MyHeartAI/android
      - name: Grant permission to Gradle wrapper
        script: chmod +x ./gradlew
      - name: Build Android APK
        script: ./gradlew assembleRelease
    artifacts:
      - MyHeartAI/android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - info@ofendaapictures.com
